name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/ci-backend.yml"
      - "backend/**"
      - "!**.md"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/ci-backend.yml"
      - "backend/**"
      - "!**.md"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: v1.47

        # Optional: working directory, useful for monorepos
        working-directory: backend
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Test
      working-directory: backend
      run: go test -v 

    - name: Build
      working-directory: backend
      run: ./scripts/Build.sh

    
